export const GENRES_OPTIONS = [
  "Action",
  "Animation",
  "Aventure",
  "Biopic",
  "Comédie",
  "Comédie dramatique",
  "Comédie musicale",
  "Court métrage",
  "Documentaire",
  "Drame",
  "Epouvante-Horreur",
  "Espionnage",
  "Famille",
  "Fantastique",
  "Guerre",
  "Historique",
  "Judiciaire",
  "Musical",
  "Policier",
  "Romance",
  "Science-fiction",
  "Thriller",
  "Western",
  "Expérimental",
  "Sport",
  "Péplum",
  "Arts martiaux",
  "Road movie",
  "Film noir",
  "Super-héros",
  "Satire",
  "Fiction",
  "Animation 3D",
  "Drame psychologique",
  "Film d’auteur",
  "Film musical",
  "Film politique",
  "Drame social",
  "Conte",
  "Enquête",
  "Adaptation littéraire",
  "Mystère",
  "Suspense",
  "Animation japonaise",
  "Animation jeunesse",
  "Film historique",
  "Dystopie",
  "Chronique",
  "Aventure humaine",
  "Cinéma engagé",
];

export const SUBTITLES_OPTIONS = ["ORIGINAL", "SUBS", "DUBBED"];
